# Generated by Django 3.0.4 on 2020-03-12 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patron',
                'verbose_name_plural': 'Patrons',
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('address', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pub',
                'verbose_name_plural': 'Pubs',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='PubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blightyapp.Pub')),
            ],
            options={
                'verbose_name': 'PubImage',
                'verbose_name_plural': 'PubImages',
            },
        ),
        migrations.AddField(
            model_name='pub',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blightyapp.Region'),
        ),
        migrations.CreateModel(
            name='PatronPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wished', models.BooleanField()),
                ('beers_tried', models.CharField(max_length=55)),
                ('food_ate', models.CharField(max_length=85)),
                ('experience', models.CharField(max_length=3000)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blightyapp.Patron')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blightyapp.Pub')),
            ],
            options={
                'verbose_name': 'patron_pub',
                'verbose_name_plural': 'patron_pubs',
            },
        ),
    ]
